apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nodejs
    spec:     # pod spec
      containers:
        - name: nodejs
          image: harbor.k-tech.cloud/kaniko/nodejs:latest # docker image name
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  ---
  
