apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
#  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nginx
    spec:     # pod spec
      containers:
      - name: nodejs
        image: harbor.k-tech.cloud/kaniko/nodejs:4
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-config-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
